# Generated by Django 5.0 on 2023-12-25 22:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count_restaurants', models.PositiveSmallIntegerField(default=1, verbose_name='Количество ресторанов')),
                ('count_menu', models.PositiveSmallIntegerField(default=5, verbose_name='Количество меню')),
                ('count_menu_items', models.PositiveSmallIntegerField(default=15, verbose_name='Количество позиций в меню')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.base')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.base')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/', verbose_name='Картика')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видемость')),
                ('working_hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время работы')),
                ('wifi_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='wifi')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
            },
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='Restaurateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurateur/')),
                ('job_title', models.CharField(max_length=255)),
                ('is_visible_restaurants', models.BooleanField(default=True)),
                ('rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.rate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ресторатор',
                'verbose_name_plural': 'Рестораторы',
            },
        ),
        migrations.AddField(
            model_name='base',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.restaurateur', verbose_name='Ресторатор'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.base')),
                ('name', models.CharField(max_length=255)),
                ('category_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.category')),
            ],
            bases=('base.base',),
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.restaurant'),
        ),
    ]
