# Generated by Django 5.0 on 2023-12-14 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count_restaurants', models.PositiveSmallIntegerField(default=1, verbose_name='Количество ресторанов')),
                ('count_menu', models.PositiveSmallIntegerField(default=5, verbose_name='Количество меню')),
                ('count_menu_items', models.PositiveSmallIntegerField(default=15, verbose_name='Количество позиций в меню')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Restaurateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jobTitle', models.CharField(max_length=255)),
                ('rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.rate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ресторатор',
                'verbose_name_plural': 'Рестораторы',
            },
        ),
    ]
