# Generated by Django 5.0 on 2023-12-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurateur',
            name='isVisibleRestaurants',
            field=models.BooleanField(default=True),
        ),
    ]
