# Generated by Django 5.0 on 2023-12-25 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='restaurant_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.restaurant'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category'),
        ),
    ]
