# Generated by Django 5.0 on 2023-12-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_base_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='isVisible',
            new_name='is_visible',
        ),
        migrations.RenameField(
            model_name='restaurateur',
            old_name='isVisibleRestaurants',
            new_name='is_visible_restaurants',
        ),
        migrations.RenameField(
            model_name='restaurateur',
            old_name='jobTitle',
            new_name='job_title',
        ),
    ]
