# Generated by Django 5.0 on 2023-12-20 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.base')),
                ('name', models.CharField(max_length=255)),
                ('category_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
            ],
            bases=('base.base',),
        ),
    ]
