# Generated by Django 5.0 on 2023-12-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='wifi'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видемость'),
        ),
    ]
