# Generated by Django 5.0 on 2024-01-30 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_menu_item_menuitemprice_menu_item_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemprice',
            name='id',
        ),
        migrations.AddField(
            model_name='menuitemprice',
            name='base_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.base'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitemprice',
            name='menu_item_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='base.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitemprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemprice',
            name='size_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
